### ISSUE TITLE
TypeError: OC_App::checkAppDependencies(): Argument #3 ($info) must be of type array, null given, called in /lib/private/legacy/OC_App.php on line 1001 and defined in /lib/private/legacy/OC_App.php:1197

### ISSUE THREAD

**Issue by gjedeer** [nextcloud/notify_push#151]
`occ upgrade` stopped at notify_push app because:

```
Update app notify_push from App Store
An unhandled exception has been thrown:
TypeError: OC_App::checkAppDependencies(): Argument #3 ($info) must be of type array, null given, called in /var/www/html/lib/private/legacy/OC_App.php on line 1001 and defined in /var/www/html/lib/private/legacy/OC_App.php:1197
Stack trace:
#0 /var/www/html/lib/private/legacy/OC_App.php(1001): OC_App::checkAppDependencies(Object(OC\AllConfig), Object(OC\L10N\LazyL10N), NULL, false)
#1 /var/www/html/lib/private/Installer.php(201): OC_App::updateApp('notify_push')
#2 /var/www/html/lib/private/Updater.php(415): OC\Installer->updateAppstoreApp('notify_push')
#3 /var/www/html/lib/private/Updater.php(277): OC\Updater->upgradeAppStoreApps(Array, Array)
#4 /var/www/html/lib/private/Updater.php(133): OC\Updater->doUpgrade('23.0.0.10', '23.0.0.10')
#5 /var/www/html/core/Command/Upgrade.php(235): OC\Updater->upgrade()
#6 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/console.php(99): OC\Console\Application->run()
#12 /var/www/html/occ(11): require_once('/var/www/html/c...')

```

I managed to get NC running, but can't install or remove the notify_push app.

```
gdr@docker:~/docker/nextcloud$ docker-compose exec --user www-data app php occ app:remove notify_push
notify_push disabled
notify_push 0 removed
gdr@docker:~/docker/nextcloud$ docker-compose exec --user www-data app php occ app:install notify_push
notify_push already installed
gdr@docker:~/docker/nextcloud$ docker-compose exec --user www-data app php occ app:enable notify_push
App "notify_push" cannot be installed because appinfo file cannot be read.

gdr@docker:~/docker/nextcloud$ docker-compose exec --user www-data app php occ notify_push:setup https://**********/push

                                                                 
  There are no commands defined in the "notify_push" namespace.  
                                                                
```

There are no files realated to notify_push:

```
gdr@docker:~/docker/nextcloud$ docker-compose exec --user www-data app ls apps/
accessibility  cloud_federation_api  dav                   files             files_sharing      firstrunwizard           notifications    privacy           settings       systemtags             updatenotification  weather_status
activity       comments              encryption            files_external    files_trashbin     logreader                oauth2           provisioning_api  sharebymail    text                   user_ldap           workflowengine
admin_audit    contactsinteraction   federatedfilesharing  files_pdfviewer   files_versions     lookup_server_connector  password_policy  recommendations   support        theming                user_status
circles        dashboard             federation            files_rightclick  files_videoplayer  nextcloud_announcements  photos           serverinfo        survey_client  twofactor_backupcodes  viewer

```

**Comment by gjedeer** [comment]
Fixed after updating to NC25
