### ISSUE TITLE
TypeError: strrpos(): Argument #1 ($haystack) must be of type string, bool given in /apps/notify_push/lib/SelfTest.php:197

### ISSUE THREAD

**Issue by solracsf** [nextcloud/notify_push#154]
Nextcloud 22.2.3.

`./occ notify_push:self-test`

```
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
An unhandled exception has been thrown:
TypeError: strrpos(): Argument #1 ($haystack) must be of type string, bool given in /apps/notify_push/lib/SelfTest.php:197
Stack trace:
#0 /apps/notify_push/lib/SelfTest.php(197): strrpos()
#1 /apps/notify_push/lib/Command/SelfTest.php(61): OCA\NotifyPush\SelfTest->test()
#2 /3rdparty/symfony/console/Command/Command.php(255): OCA\NotifyPush\Command\SelfTest->execute()
#3 /3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#7 /console.php(99): OC\Console\Application->run()
#8 /occ(11): require_once('...')
#9 {main}
```

**Comment by DrZoidberg09** [comment]
Same here with 23.0.4

**Comment by francoisPE** [comment]
Same with 24.0.4 when running manual setup ./occ notify_push:setup https://mync.tld/push

**Comment by francoisPE** [comment]
Investigating a bit, I see that notify_push is not going through getAppVersion/getAppinfo in lib/private/App/AppManager.php

**Comment by francoisPE** [comment]
I an still investigationg that
I run a test_client https://mync.tld user pass
it gives
```
[2022-10-14 22:20:52.788557 +02:00] INFO [test_client] test_client/src/main.rs:29: Found push server at wss://mync.tld/push/ws
Error:
  × Can't connect to server
  ├─▶ WebSocket protocol error: Missing, duplicated or incorrect header sec-websocket-key
  ╰─▶ Missing, duplicated or incorrect header sec-websocket-key
```
when I run
php occ notify_push:self-test
it gives
```
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
An unhandled exception has been thrown:
TypeError: strrpos(): Argument #1 ($haystack) must be of type string, bool given in /var/www/clients/client0/web4/web/apps/notify_push/lib/SelfTest.php:196
Stack trace:
#0 /var/www/clients/client0/web4/web/apps/notify_push/lib/SelfTest.php(196): strrpos()
#1 /var/www/clients/client0/web4/web/apps/notify_push/lib/Command/SelfTest.php(61): OCA\NotifyPush\SelfTest->test()
#2 /var/www/clients/client0/web4/web/3rdparty/symfony/console/Command/Command.php(255): OCA\NotifyPush\Command\SelfTest->execute()
#3 /var/www/clients/client0/web4/web/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#4 /var/www/clients/client0/web4/web/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/clients/client0/web4/web/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#6 /var/www/clients/client0/web4/web/lib/private/Console/Application.php(211): Symfony\Component\Console\Application->run()
#7 /var/www/clients/client0/web4/web/console.php(100): OC\Console\Application->run()
#8 /var/www/clients/client0/web4/web/occ(11): require_once('...')
```

I am now more or less convinced that's an issue of proxy.
How can I test specifically that ?

I run appache2
I set 
```
ProxyPass /push/ws ws://127.0.0.1:50004/ws
ProxyPass /push/ http://127.0.0.1:50004/
ProxyPassReverse /push/ http://127.0.0.1:50004/
```
Obviously notify_push server is on port 50004. The first test with test_cleint shows that's not the issue because a server is found.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/notify_push/issues/191#issuecomment-1290548234
