### ISSUE TITLE
Redis : don’t use dbindex if cluster mode

### ISSUE THREAD

**Issue by ldidry** [nextcloud/notify_push#378]
Hello,

I made a mistake in my configuration and let a `dbindex` setting for the redis config, but as I am using a Redis cluster, there is no multiple databases so I got this failure:

```
Failed to setup redis subscription: Redis server refused to switch database- ResponseError
Redis server disconnected, reconnecting in 1s
```

Nextcloud does not complain as they behave differently between cluster or normal mode (see https://github.com/nextcloud/server/blob/master/lib/private/RedisFactory.php#L79).

I think that notify_push should do the same.

(obviously, I removed the `dbindex` setting and it works now)

**Comment by yodatak** [comment]
Hi got the same problem when i add
a dbindex in my config it failed but when i remove it the test pass

sudo -u nextcloud php8.4 -f /var/www/html/cloud.solidairesinformatique.org/occ notify_push:self-test

    "redis" => [
        "host" => "127.0.0.1",
        "port" => 6380,
        "password" => "XXXX",
        "dbindex" => 5,
    ],

**Comment by yodatak** [comment]
✘ ⚡ root@XXXX  /etc/netdata   master  sudo -u nextcloud php8.4 -f /var/www/html/cloud.XXXXX.org/occ notify_push:self-test
✓ redis is configured
✓ push server is receiving redis messages
✓ push server can load mount info from database
✓ push server can connect to the Nextcloud server
✓ push server is a trusted proxy
An unhandled exception has been thrown:
TypeError: strrpos(): Argument #1 ($haystack) must be of type string, false given in /var/www/html/cloud.XXXX.org/apps/notify_push/lib/SelfTest.php:197
Stack trace:
#0 /var/www/html/cloud.XXX.org/apps/notify_push/lib/SelfTest.php(197): strrpos()
#1 /var/www/html/cloud.XXXX.org/apps/notify_push/lib/Command/SelfTest.php(46): OCA\NotifyPush\SelfTest->test()
#2 /var/www/html/cloud.XXX.org/3rdparty/symfony/console/Command/Command.php(326): OCA\NotifyPush\Command\SelfTest->execute()
#3 /var/www/html/cloud.XXX.org/3rdparty/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#4 /var/www/html/cloud.XXX.org/3rdparty/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#5 /var/www/html/cloud.XXX.org/3rdparty/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun()
#6 /var/www/html/cloud.XXX.org/lib/private/Console/Application.php(187): Symfony\Component\Console\Application->run()
#7 /var/www/html/cloud.XXX.org/console.php(87): OC\Console\Application->run()
#8 /var/www/html/cloud.XXXX.org/occ(33): require_once('...')
#9 {main}#

**Comment by icewind1991** [comment]
@yodatak can you provide the output of `notify_push --dump-config <path-to-config.php>`
